# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bcedd13fded56b0c76571f5e5159fd945f7140c10f6d5d745f6ff55a13474f5efb802d44ee455b07d17126a95ae21078e241eed5c3bb6357958e38706f4a1fe

  google_map_url: https://maps.googleapis.com/maps/api/js?
  google_place_url: https://maps.googleapis.com/maps/api/place/textsearch/json?
  google_detail_url: https://maps.googleapis.com/maps/api/place/details/json?
  google_photo_url: https://maps.googleapis.com/maps/api/place/photo?

  google_map_key: AIzaSyBR5W0NXLtkq2KfxhpOuOh7lQd9h-SaOuA
  google_place_key: AIzaSyD_mMKLGBULdpg7KvEFfdoHQpdbu83EG-Q
  google_photo_key: AIzaSyD_mMKLGBULdpg7KvEFfdoHQpdbu83EG-Q

  mailer_user: xxx@gmail.com
  mailer_pass: xxxxxxx

test:
  secret_key_base: 2c52220df2a134db10ff0031d753f1f67f3ba72b3601213dab9695b02653a662d054fb9e349cc4c060c2fcd763fa752a12f6a768193c9eb5bf25aa236ef562c4

  google_map_url: https://maps.googleapis.com/maps/api/js?
  google_place_url: https://maps.googleapis.com/maps/api/place/textsearch/json?
  google_detail_url: https://maps.googleapis.com/maps/api/place/details/json?
  google_photo_url: https://maps.googleapis.com/maps/api/place/photo?

  google_map_key: AIzaSyBR5W0NXLtkq2KfxhpOuOh7lQd9h-SaOuA
  google_place_key: AIzaSyD_mMKLGBULdpg7KvEFfdoHQpdbu83EG-Q
  google_photo_key: AIzaSyD_mMKLGBULdpg7KvEFfdoHQpdbu83EG-Q

  mailer_user: xxx@gmail.com
  mailer_pass: xxxxxxx

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  google_map_url: https://maps.googleapis.com/maps/api/js?
  google_place_url: https://maps.googleapis.com/maps/api/place/textsearch/json?
  google_detail_url: https://maps.googleapis.com/maps/api/place/details/json?
  google_photo_url: https://maps.googleapis.com/maps/api/place/photo?

  google_map_key: AIzaSyBR5W0NXLtkq2KfxhpOuOh7lQd9h-SaOuA
  google_place_key: AIzaSyD_mMKLGBULdpg7KvEFfdoHQpdbu83EG-Q
  google_photo_key: AIzaSyD_mMKLGBULdpg7KvEFfdoHQpdbu83EG-Q

  mailer_user: xxx@gmail.com
  mailer_pass: xxxxxxx
